import { MONO, esc } from './theme.mjs';
import { morse } from './morse.mjs';
import { pulse, seamlessTranslate, staggerBrighten } from './svg-motion.mjs';

const W = 1000;
const H = 340;

const NAME = 'ANURAGH K P';

// Carrier geometry. WAVELENGTH must divide the drawn width evenly so that
// translating by exactly one wavelength returns to the starting image.
const WAVELENGTH = 50;
const CARRIER_Y = 218;
const CARRIER_LEFT = 40;
const CARRIER_RIGHT = 960;

const PEAKS = [
  { x: 190, height: 40, width: 30, label: 'rust' },
  { x: 415, height: 30, width: 26, label: 'laravel' },
  { x: 640, height: 46, width: 24, label: 'sdr' },
  { x: 845, height: 26, width: 28, label: 'local-ai' },
];

// Morse keying geometry, proportioned to real timing: dah = 3 dits.
const DIT = 8;
const DAH = 24;
const ELEMENT_GAP = 8;
const CHAR_GAP = 18;
const WORD_GAP = 34;
const MORSE_Y = 136;
const MORSE_HEIGHT = 7;
const MORSE_CYCLE = 9;

function envelope(x) {
  let lift = 6;
  for (const peak of PEAKS) {
    const d = (x - peak.x) / peak.width;
    lift += peak.height * Math.exp(-d * d);
  }
  return lift;
}

// Outline of the modulation envelope, drawn statically above and below the
// carrier so the shape of the modulation is legible even while the wave moves.
function envelopeOutline(sign) {
  const points = [];
  for (let x = CARRIER_LEFT; x <= CARRIER_RIGHT; x += 4) {
    points.push(`${x},${(CARRIER_Y - sign * envelope(x)).toFixed(1)}`);
  }
  return `M${points.join(' L')}`;
}

// A genuinely amplitude-modulated carrier: y = envelope(x) * sin(phase).
//
// The wave is animated by interpolating between phase-shifted copies of the
// path rather than by translating it. Translation would drag the envelope along
// with the wave, and masking a constant-amplitude sine only clips it into
// disconnected slashes — neither produces amplitude modulation. Because every
// copy is generated by the same loop, all paths share an identical node count,
// which is what SMIL requires to interpolate `d`.
const PHASE_STEPS = 10;
const CARRIER_SAMPLE = 5;

function carrierPathAtPhase(phase) {
  const points = [];
  for (let x = CARRIER_LEFT; x <= CARRIER_RIGHT; x += CARRIER_SAMPLE) {
    const y = CARRIER_Y - envelope(x) * Math.sin((2 * Math.PI * x) / WAVELENGTH + phase);
    points.push(`${x},${y.toFixed(2)}`);
  }
  return `M${points.join(' L')}`;
}

function carrierPhases() {
  const paths = [];
  for (let step = 0; step <= PHASE_STEPS; step += 1) {
    // Negative phase makes the wave travel left to right.
    paths.push(carrierPathAtPhase((-2 * Math.PI * step) / PHASE_STEPS));
  }
  return paths;
}

function morseBars(theme) {
  const encoded = morse(NAME);
  const elements = [];
  let index = 0;

  const total = encoded.reduce((sum, entry) => sum + entry.symbols.length, 0);

  let x = 43;
  for (const entry of encoded) {
    if (entry.symbols === '') {
      x += WORD_GAP;
      continue;
    }
    for (const symbol of entry.symbols) {
      const width = symbol === '-' ? DAH : DIT;
      elements.push(
        `<rect class="morse-el" x="${x}" y="${MORSE_Y}" width="${width}" height="${MORSE_HEIGHT}" rx="1.5" fill="${theme.carrier}">`
        + staggerBrighten({ index, count: total, cycle: MORSE_CYCLE, rest: 0.35 })
        + '</rect>',
      );
      x += width + ELEMENT_GAP;
      index += 1;
    }
    x += CHAR_GAP - ELEMENT_GAP;
  }
  return elements.join('');
}

// Every row draws the same pattern; the fade comes from a static gradient
// overlay. Baking decay per row would break the seamless loop.
function waterfall(theme) {
  const cellW = 19;
  const pitch = 16;
  const rows = [];
  for (let row = -1; row < 3; row += 1) {
    const y = 292 + row * pitch;
    const cells = [];
    for (let i = 0; i < 48; i += 1) {
      const x = 40 + i * cellW;
      const strength = Math.min(1, envelope(x + cellW / 2) / 48);
      const opacity = 0.1 + strength * 0.65;
      cells.push(
        `<rect x="${x}" y="${y}" width="${cellW - 3}" height="12" fill="${theme.carrier}" opacity="${opacity.toFixed(3)}"/>`,
      );
    }
    rows.push(cells.join(''));
  }
  return `<g>${rows.join('')}${seamlessTranslate({ dy: pitch, dur: '3s' })}</g>`;
}

function peakMarkers(theme) {
  return PEAKS.map((peak) => {
    const y = CARRIER_Y - envelope(peak.x);
    return `<circle cx="${peak.x}" cy="${y.toFixed(1)}" r="3.5" fill="${theme.peak}"/>`
      + `<line x1="${peak.x}" y1="${(y + 6).toFixed(1)}" x2="${peak.x}" y2="264" stroke="${theme.peak}" stroke-width="1" opacity="0.45"/>`
      + `<text x="${peak.x}" y="276" font-family="${MONO}" font-size="11" fill="${theme.muted}" text-anchor="middle">${esc(peak.label)}</text>`;
  }).join('');
}

export function renderHero(theme) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" role="img" aria-label="Anuragh K P — full stack developer, Vatakara. Name in Morse code over a modulated carrier wave and spectrum waterfall.">
<defs>
<clipPath id="waterfall-clip">
<rect x="40" y="288" width="920" height="48"/>
</clipPath>
<linearGradient id="waterfall-fade" x1="0" y1="0" x2="0" y2="1">
<stop offset="0" stop-color="${theme.ground}" stop-opacity="0"/>
<stop offset="1" stop-color="${theme.ground}" stop-opacity="0.95"/>
</linearGradient>
</defs>
<rect width="${W}" height="${H}" fill="${theme.ground}"/>
<text x="40" y="26" font-family="${MONO}" font-size="12" fill="${theme.muted}" letter-spacing="1.5">anuragh@vatakara</text>
<g>
<circle cx="928" cy="22" r="4" fill="${theme.peak}">${pulse({ values: '1;0.25;1', dur: '2.4s' })}</circle>
<text x="942" y="26" font-family="${MONO}" font-size="12" fill="${theme.peak}" letter-spacing="2">RX</text>
</g>
<line x1="40" y1="40" x2="960" y2="40" stroke="${theme.grid}" stroke-width="1"/>
<text x="40" y="110" font-family="${MONO}" font-size="50" font-weight="700" fill="${theme.text}" letter-spacing="13">${esc(NAME)}</text>
${morseBars(theme)}
<path d="${envelopeOutline(1)}" fill="none" stroke="${theme.carrier}" stroke-width="1" opacity="0.28"/>
<path d="${envelopeOutline(-1)}" fill="none" stroke="${theme.carrier}" stroke-width="1" opacity="0.28"/>
<path d="${carrierPhases()[0]}" fill="none" stroke="${theme.carrier}" stroke-width="2" stroke-linejoin="round">
<animate attributeName="d" values="${carrierPhases().join(';')}" dur="1.6s" repeatCount="indefinite"/>
</path>
<line x1="40" y1="256" x2="960" y2="256" stroke="${theme.grid}" stroke-width="1"/>
${peakMarkers(theme)}
<g clip-path="url(#waterfall-clip)">
${waterfall(theme)}
<rect x="40" y="288" width="920" height="48" fill="url(#waterfall-fade)"/>
</g>
</svg>`;
}
